### ISSUE TITLE
Create repository for mobile app with existing functionality

### ISSUE THREAD

**Issue by miron4dev** [motivepick/motive-back-end#3]
motive-mobile-app

**Comment by yaskovdev** [comment]
<img width="464" alt="2018-08-12 10 22 57" src="https://user-images.githubusercontent.com/7571738/43999673-e3cca18e-9e19-11e8-9dd2-3dd4e4747779.png">
<img width="460" alt="2018-08-12 10 21 28" src="https://user-images.githubusercontent.com/7571738/43999674-e3e731c0-9e19-11e8-84e7-3cbad5c0809b.png">
