### ISSUE TITLE
Buy domain

### ISSUE THREAD

**Issue by miron4dev** [motivepick/motive-back-end#9]
- motief.ru (https://www.reg.ru/choose/domain/?is_bulk_registration=&domains=motief.ru)
- motivacija.org (https://www.reg.ru/choose/domain/?domains=motivacija.org&is_bulk_registration=)
- motivashki.com
- movente.su

**Comment by yaskovdev** [comment]
Do not forget to update the link on the organization page, add the links to each repository (both README.md and title) and configure Google Console for the new domain.

**Comment by miron4dev** [comment]
https://motivepick.com is up and running
README.md will be updated after load balancing and DB replication configuration
See #10
